Repository livarter/backend, pull requests merged in 2024-01, with the labels that each got.

#2 Feature/security Spring Security + Kakao OAuth + 자체 JWT 로그인 구현
  pom.xml
  src/main/java/com/livarter/app/config/CorsConfig.java
  src/main/java/com/livarter/app/config/RootContextConfig.java
  src/main/java/com/livarter/app/config/SecurityConfig.java
  src/main/java/com/livarter/app/config/WebConfig.java
  src/main/java/com/livarter/app/controller/AuthController.java
  src/main/java/com/livarter/app/controller/MemberController.java
  src/main/java/com/livarter/app/domain/Member.java
  src/main/java/com/livarter/app/domain/enumType/Grade.java
  src/main/java/com/livarter/app/domain/enumType/Header.java
  src/main/java/com/livarter/app/domain/enumType/Nickname.java
  src/main/java/com/livarter/app/domain/enumType/OAuthType.java
  src/main/java/com/livarter/app/domain/enumType/Role.java
  src/main/java/com/livarter/app/dto/MemberResDto.java
  src/main/java/com/livarter/app/mapper/MemberMapper.java
  src/main/java/com/livarter/app/security/AuthDetailsService.java
  src/main/java/com/livarter/app/security/AuthTokenAccessDeniedHandler.java
  src/main/java/com/livarter/app/security/AuthTokenAuthenticationEntryPoint.java
  src/main/java/com/livarter/app/security/AuthTokenFilter.java
  src/main/java/com/livarter/app/security/AuthTokenFilterConfigurer.java
  src/main/java/com/livarter/app/security/AuthTokenGenerator.java
  src/main/java/com/livarter/app/security/KakaoOauthClient.java
  src/main/java/com/livarter/app/security/SecurityWebApplicationInitializer.java
  src/main/java/com/livarter/app/security/dto/KakaoResDto.java
  src/main/java/com/livarter/app/security/dto/LoginReqDto.java
  src/main/java/com/livarter/app/security/dto/LoginResDto.java
  src/main/java/com/livarter/app/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mapper/MemberMapper.xml
Labels: feature

#4 feat: 회원 정보 수정 기능 추가
  .gitignore
  src/main/java/com/livarter/app/controller/MemberController.java
  src/main/java/com/livarter/app/dto/MemberUpdateReqDto.java
  src/main/java/com/livarter/app/mapper/MemberMapper.java
  src/main/java/com/livarter/app/service/MemberService.java
  src/main/resources/mapper/MemberMapper.xml
Labels: enhancement

#10 feat: 주문내역/상세내역 저장 및 조회
  pom.xml
  src/main/java/com/livarter/app/config/SecurityConfig.java
  src/main/java/com/livarter/app/controller/PurchaseController.java
  src/main/java/com/livarter/app/domain/HistoryDetail.java
  src/main/java/com/livarter/app/domain/PurchaseHistory.java
  src/main/java/com/livarter/app/dto/PurchaseHistoryResDto.java
  src/main/java/com/livarter/app/dto/PurchaseReqDto.java
  src/main/java/com/livarter/app/mapper/HistoryDetailMapper.java
  src/main/java/com/livarter/app/mapper/PurchaseHistoryMapper.java
  src/main/java/com/livarter/app/service/PurchaseHistoryServiceImpl.java
  src/main/java/com/livarter/app/service/PurchaseHistroryService.java
  src/main/resources/mapper/PurchaseHistoryMapper.xml
Labels: feature

#11 Feature/search api
  src/main/java/com/livarter/app/controller/ProductController.java
Labels: bug

#13 Feature/badge 뱃지 등록 및 조회 기능 구
  src/main/java/com/livarter/app/controller/BadgeController.java
  src/main/java/com/livarter/app/domain/Badge.java
  src/main/java/com/livarter/app/domain/BadgeMember.java
  src/main/java/com/livarter/app/dto/BadgeMemberListDto.java
  src/main/java/com/livarter/app/dto/BadgeResDto.java
  src/main/java/com/livarter/app/mapper/BadgeMapper.java
  src/main/java/com/livarter/app/service/BadgeService.java
  src/main/java/com/livarter/app/service/BadgeServiceImpl.java
  src/main/java/com/livarter/app/service/MemberService.java
  src/main/resources/mapper/BadgeMapper.xml
Labels: feature

#18 Dto 타입 변경 URI 수정
  src/main/java/com/livarter/app/controller/PurchaseController.java
  src/main/java/com/livarter/app/dto/PurchaseHistoryResDto.java
  src/main/resources/mapper/PurchaseHistoryMapper.xml
Labels: enhancement

#19 feat: 주문시 memberId 적용
  src/main/java/com/livarter/app/config/SecurityConfig.java
  src/main/java/com/livarter/app/controller/PurchaseController.java
  src/main/java/com/livarter/app/dto/PurchaseReqDto.java
  src/main/java/com/livarter/app/mapper/PurchaseHistoryMapper.java
  src/main/java/com/livarter/app/service/PurchaseHistoryServiceImpl.java
  src/main/java/com/livarter/app/service/PurchaseHistroryService.java
  src/main/resources/mapper/PurchaseHistoryMapper.xml
Labels: enhancement

#21 댓글 reply MVC 완성
  src/main/java/com/livarter/app/config/SecurityConfig.java
  src/main/java/com/livarter/app/controller/ReplyController.java
  src/main/java/com/livarter/app/domain/Reply.java
  src/main/java/com/livarter/app/dto/GetReplyDto.java
  src/main/java/com/livarter/app/mapper/ReplyMapper.java
  src/main/java/com/livarter/app/service/ReplyService.java
  src/main/java/com/livarter/app/service/ReplyServiceImpl.java
  src/main/resources/mapper/ReplyMapper.xml
Labels: feature

#23 Feature/member event 뱃지/쿠폰 발급 시 팝업창으로 띄울 res 반환 기능 구현
  src/main/java/com/livarter/app/controller/AuthController.java
  src/main/java/com/livarter/app/controller/MemberController.java
  src/main/java/com/livarter/app/domain/Badge.java
  src/main/java/com/livarter/app/domain/BadgeMember.java
  src/main/java/com/livarter/app/mapper/BadgeMapper.java
  src/main/java/com/livarter/app/mapper/MemberMapper.java
  src/main/java/com/livarter/app/mapper/ReplyMapper.java
  src/main/java/com/livarter/app/membership/MemberEventController.java
  src/main/java/com/livarter/app/membership/MemberEventHandler.java
  src/main/java/com/livarter/app/membership/dto/BadgeType.java
  src/main/java/com/livarter/app/membership/dto/CouponType.java
  src/main/java/com/livarter/app/membership/dto/PopUpDto.java
  src/main/resources/mapper/BadgeMapper.xml
  src/main/resources/mapper/MemberMapper.xml
  src/main/resources/mapper/ReplyMapper.xml
Labels: feature

#24 리뷰 get/set에 reply_img 추가
  src/main/java/com/livarter/app/controller/ReplyController.java
  src/main/java/com/livarter/app/domain/Reply.java
  src/main/java/com/livarter/app/dto/GetReplyDto.java
  src/main/java/com/livarter/app/service/ReplyService.java
  src/main/java/com/livarter/app/service/ReplyServiceImpl.java
  src/main/resources/mapper/ReplyMapper.xml
Labels: feature
